[package]
name = "aircraft-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "aircraft"
path = "src/main.rs"

[dependencies]
aircraft-engine = { version = "0.1.0", path = "../../crates/aircraft-engine" }
aircraft-graph = { version = "0.1.0", path = "../../crates/aircraft-graph" }
aircraft-model = { version = "0.1.0", path = "../../crates/aircraft-model" }
meshio = { version = "0.1.0", path = "../../crates/meshio" }
clap.workspace = true

[lints]
workspace = true
